### ISSUE TITLE
Tree does hover only ~20nodes up

### ISSUE THREAD

**Issue by tchncs** [duane-r/integral#1]
Hi there i am not sure if i misunderstood the readme since english is not my primary language.
I just found an integral tree hovering around 20-30* nodes from the ground and "crashes" into a hill:

![screenshot_20170305_120921](https://cloud.githubusercontent.com/assets/10698140/23586866/cf1063a2-019e-11e7-825d-9b133f9c418a.jpg)

As i understood the readme whey should start at ~200 nodes + only.

By the way, how can i change this in general? I am not sure if i understand all the calculating.
The mapgen of my upcoming server will produce mountains upto 1k and more so the integral trees are supposed to spawn at ~ 2k or so. A hint would be very awesome. :)

###### * i am not sure about the actual hover height since it is in a hill

**Comment by duane-r** [comment]
That's normal behavior. I can't adjust their height since the only place heightmaps actually work is in the chunk where the ground is, so I just placed them at a workable altitude. Sometimes the ground is high enough that they intersect. If it really bothers you, you can adjust the constant (100) in line 33 of mapgen.lua.

`d.pos.y = math.floor(100 + d.height * 0.5)`

The only problem is, they won't be visible from the ground most of the time. (It's hard to see them sometimes as it is.)

**Comment by tchncs** [comment]
Okey, thank you 👍
